<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Practice</title>
    <link rel="stylesheet" href="/lesson-16/lesson16.css">
    <script src="practice.js"></script>
    <img id="norImg" src="/JavaScript-logo.png" alt="">

</head>
<body>
    <h1 id="speH1">PRACTICE for errors and exceptions</h1>
    <h2>SECTION PRACTICE</h2>
    <p>
        <b id="front">Exercise 1:</b> Write your own <b id="spePara">div</b> function that will take two call arguments and return the result of dividing the first argument by the second. 
        In JavaScript, the result of dividing by zero is the value <b id="spePara">Infinity</b> (or <b id="spePara">-Infinity</b>, if we try to divide a negative number). Change this. If you pass <b id="spePara">0</b> as the second argument, 
        your function should throw a <b id="spePara">RangeError</b> exception with the appropriate message. Prepare a test call of the function for both valid division and division by zero.
    </p>
    <p>
        <b id="front">Exercise 2:</b> The following array of numbers has been declared: <br>
        <pre>
            <code>
                let numbers = [10, 40, 0, 20, 50];
            </code>
        </pre>
        Write a program that, in a loop, divides the number 1000 by successive elements of the <b id="spePara">numbers</b> array, displaying the result of each division. 
        To divide the numbers, use the function from the previous task. Use the <b id="spepara">try...catch</b> construction to handle an exception thrown in the case of division by zero. 
        If such an exception is caught, the program should print an appropriate message (taken from the exception) and continue its operation (division by successive elements of the array).
    </p>
</body>
</html>